name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main  # change if your default branch is different

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create config.js
        run: |
          echo "export const OMDB_API_KEY = '${{ secrets.OMDB_API_KEY }}';" > config.js
          echo "export const YOUTUBE_API_KEY = '${{ secrets.YOUTUBE_API_KEY }}';" >> config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # deploy everything in root















